### PR TITLE
Updates composer dependencies

### PR DESCRIPTION
**Pull request by BOPOH**
Add support for illuminate/support v9.0 and v10.0

### CODE REVIEW

**Comment by gigorok** [comment]
Hello @BOPOH,

Thanks for your contributions!
By this pull request, you suggest adding support for `illuminate/support` v9.0 and v10.0, right?

**Comment by BOPOH** [comment]
Yes, current dependencies prevent us from completely upgrading to Symfony 7:
- `didww/didww-api-3-php-sdk: 6.1` requires [`illuminate/support: ^5.5|^6.0|^7.0|^8.0`](https://github.com/didww/didww-api-3-php-sdk/blob/master/composer.json#L19C8-L19C26)
- `illuminate/support: 8.0` (current dependency) requires [`illuminate/contracts: ^8.0`](https://github.com/illuminate/support/blob/v8.83.27/composer.json#L22)
- `illuminate/contracts: 8.0` requires [`psr/container: ^1.0`](https://github.com/illuminate/contracts/blob/v8.83.27/composer.json#L18)   

at the same time
- `symfony/dependency-injection: 7.0` requires [`symfony/service-contracts: ^3.3`](https://github.com/symfony/dependency-injection/blob/v7.0.0/composer.json#L22)
- `symfony/service-contracts: 3.3` requires [`psr/container: ^2.0`](https://github.com/symfony/service-contracts/blob/v3.3.0/composer.json#L20)   

i.e. we have conflicts here with version of `psr/container`.   

Update to `illuminate/support: 9.0-10.0` solves conflict:
- `illuminate/support: 10.0` requires [`illuminate/contracts: ^10.0`](https://github.com/illuminate/support/blob/v10.37.2/composer.json#L24)
- `illuminate/contracts: 10.0` requires [`psr/container: ^1.1.1|^2.0.1`](https://github.com/illuminate/contracts/blob/v10.37.2/composer.json#L18)

**Comment by gigorok** [comment]
@BOPOH Thanks!

**Comment by gigorok** [comment]
@BOPOH v6.2.0 released.

**Pull request merged**
